#!/usr/bin/python3
"""
This Module is To :
    Factorize as many numbers as possible
    into a product of two smaller numbers.
"""


import sys


def factorize(num):
    """
    This Function is To:
    - Find the Factorization of a Number
    """
    for i in range(2, num):
        if num % i == 0:
            return i, num // i
    return None


def main(filename):
    """
    Main Function
    - Reads <file> From Command Line and
    Passes it to <factorize> function
    """
    with open(filename, 'r') as file:
        numbers = file.read().splitlines()
    for num in numbers:
        num = int(num)
        factor = factorize(num)
        if factor:
            p, q = factor
            print("{}={}*{}".format(num, q, p))


if __name__ == "__main__":

    # Make Sure That the User Only Enters One File

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    # Get FileName and Pass it To <main> Function
    filename = sys.argv[1]
    main(filename)
