#!/usr/bin/python3
"""
This Module is To :
    Factorize as many numbers as possible
    into a product of two smaller numbers.
"""


import sys


def factorize(num):
    """
    This Function is To:
    - Find the Factorization of a Number
    """
    for i in range(2, num):
        if num % i == 0:
            return i, num // i
    return None


def is_prime(num):
    """
    Check if a number is prime.

    Args:
    - num (int): The number to be checked.

    Returns:
    - bool: True if the number is prime, False otherwise.
    """
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True


def main(filename):
    """
    Main Function
    - Reads <file> From Command Line and
    Passes it to <factorize> function
    """
    with open(filename, 'r') as file:
        numbers = file.read().splitlines()
    for num in numbers:
        num = int(num)
        if is_prime(num):
            print("{}={}*{}".format(num, num, 1))
        else:
            factor = factorize(num)
            if factor:
                p, q = factor
                print("{}={}*{}".format(num, p, q))


if __name__ == "__main__":

    # Make Sure That the User Only Enters One File

    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    # Get FileName and Pass it To <main> Function
    filename = sys.argv[1]
    main(filename)
